# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-01-08T03:17:17+00:00

from __future__ import annotations

from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel


class BaseWidget(BaseModel):
    widget_type: str = Field(..., description='Specifies the type of the widget.')
    title: str = Field(..., description='User-defined title of the widget.')


class PieChart(BaseWidget):
    table: str = Field(
        ..., description='Name of the table in the data source used for the pie chart.'
    )
    data_column: str = Field(
        ...,
        description='Name of the column used with categorical values for the pie chart.',
    )
    widget_type: Literal['PieChart']


class Datum(BaseModel):
    title: str
    count: float


class PieChartData(BaseModel):
    data: List[Datum]


class Histogram(BaseWidget):
    table: str = Field(
        ..., description='Name of the table in the data source used for the histogram.'
    )
    data_column: str = Field(
        ..., description='Name of the column with values used to build a histogram.'
    )
    widget_type: Literal['Histogram']


class HistogramData(BaseModel):
    data: List[float]


class Widget(RootModel[Union[PieChart, Histogram]]):
    root: Union[PieChart, Histogram] = Field(..., discriminator='widget_type')


class WidgetData(RootModel[Union[PieChartData, HistogramData]]):
    root: Union[PieChartData, HistogramData]


class DataSource(BaseModel):
    host: str = Field(
        ..., description='Hostname or IP address of the data source server.'
    )
    port: int = Field(
        ..., description='Port number for connecting to the data source server.'
    )
    username: str = Field(..., description='Username for data source authentication.')
    password: Optional[str] = Field(
        None, description='Password for data source authentication.'
    )
    database: str = Field(..., description='Name of the database to connect to.')


class Column(BaseModel):
    name: str = Field(..., description='Name of the column.')
    dataType: str = Field(..., description='Data type of the column.')


class DataSourceTable(BaseModel):
    name: str = Field(
        ...,
        description='Full table name, including schema, e.g., "HumanResources.Employee".',
    )
    columns: List[Column] = Field(
        ...,
        description='List of columns in the table, including their names and data types.',
    )


class Error(BaseModel):
    detail: Optional[str] = None


class GetDashboardPostRequest(BaseModel):
    dashboard_id: int


class DeleteDashboardPostRequest(BaseModel):
    dashboard_id: int


class GetDataSourceTablesPostRequest(BaseModel):
    dashboard_id: int


class GetDataSourceTablesPostResponse(RootModel[List[DataSourceTable]]):
    root: List[DataSourceTable]


class AddWidgetPostRequest(BaseModel):
    dashboard_id: int
    widget: Widget


class DeleteWidgetPostRequest(BaseModel):
    dashboard_id: int
    widget_id: int = Field(
        ..., description='Widget index withing the list of the dashboard widgets'
    )


class FetchWidgetDataPostRequest(BaseModel):
    dashboard_id: int
    widget_id: int = Field(
        ..., description='Widget index withing the list of the dashboard widgets'
    )


class Dashboard(BaseModel):
    dashboard_id: int = Field(..., description='Unique identifier for the dashboard.')
    title: str = Field(..., description='User-defined title of the dashboard.')
    widgets: List[Widget] = Field(
        ..., description='List of widgets included in the dashboard.'
    )
    dataSource: DataSource = Field(
        ...,
        description='Configuration of the data source associated with the dashboard.',
    )


class GetDashboardsPostResponse(RootModel[List[Dashboard]]):
    root: List[Dashboard]


class DeleteDashboardPostResponse(RootModel[List[Dashboard]]):
    root: List[Dashboard]
