# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-01-10T20:00:07+00:00

from __future__ import annotations

from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel


class DashboardDigest(BaseModel):
    dashboard_id: int
    title: str


class BaseWidgetCreate(BaseModel):
    widget_type: str = Field(..., description='Specifies the type of the widget.')
    title: str = Field(..., description='User-defined title of the widget.')


class BaseWidget(BaseModel):
    widget_type: str = Field(..., description='Specifies the type of the widget.')
    widget_id: int = Field(..., description='Unique identifier for the widget.')
    title: str = Field(..., description='User-defined title of the widget.')


class PieChartCreate(BaseWidgetCreate):
    table: str = Field(
        ..., description='Name of the table in the data source used for the pie chart.'
    )
    data_column: str = Field(
        ...,
        description='Name of the column used with categorical values for the pie chart.',
    )
    widget_type: Literal['PieChart']


class PieChartDatum(BaseModel):
    title: str
    count: int


class PieChartData(RootModel[List[PieChartDatum]]):
    root: List[PieChartDatum]


class HistogramCreate(BaseWidgetCreate):
    table: str = Field(
        ..., description='Name of the table in the data source used for the histogram.'
    )
    data_column: str = Field(
        ..., description='Name of the column with values used to build a histogram.'
    )
    widget_type: Literal['Histogram']


class HistogramData(RootModel[List[float]]):
    root: List[float]


class WidgetCreate(RootModel[Union[PieChartCreate, HistogramCreate]]):
    root: Union[PieChartCreate, HistogramCreate] = Field(
        ..., discriminator='widget_type'
    )


class DataSourceCreate(BaseModel):
    host: str = Field(
        ..., description='Hostname or IP address of the data source server.'
    )
    port: int = Field(
        ..., description='Port number for connecting to the data source server.'
    )
    username: str = Field(..., description='Username for data source authentication.')
    password: Optional[str] = Field(
        None, description='Password for data source authentication.'
    )
    database: str = Field(..., description='Name of the database to connect to.')


class Column(BaseModel):
    name: str = Field(..., description='Name of the column.')
    dataType: str = Field(..., description='Data type of the column.')


class DataSourceTable(BaseModel):
    name: str = Field(
        ...,
        description='Full table name, including schema, e.g., "HumanResources.Employee".',
    )
    columns: List[Column] = Field(
        ...,
        description='List of columns in the table, including their names and data types.',
    )


class Error(BaseModel):
    detail: Optional[str] = None


class GetDashboardsPostRequest(BaseModel):
    pass


class GetDashboardsPostResponse(RootModel[List[DashboardDigest]]):
    root: List[DashboardDigest]


class GetDashboardPostRequest(BaseModel):
    dashboard_id: int


class DeleteDashboardPostRequest(BaseModel):
    dashboard_id: int


class DeleteDashboardPostResponse(RootModel[List[DashboardDigest]]):
    root: List[DashboardDigest]


class AddWidgetPostRequest(BaseModel):
    dashboard_id: int
    widget: WidgetCreate


class DeleteWidgetPostRequest(BaseModel):
    dashboard_id: int
    widget_id: int


class DashboardCreate(BaseModel):
    title: str = Field(..., description='User-defined title of the dashboard.')
    dataSource: DataSourceCreate


class PieChart(BaseWidget):
    table: str = Field(
        ..., description='Name of the table in the data source used for the pie chart.'
    )
    data_column: str = Field(
        ...,
        description='Name of the column used with categorical values for the pie chart.',
    )
    data: PieChartData
    widget_type: Literal['PieChart']


class Histogram(BaseWidget):
    table: str = Field(
        ..., description='Name of the table in the data source used for the histogram.'
    )
    data_column: str = Field(
        ..., description='Name of the column with values used to build a histogram.'
    )
    data: HistogramData
    widget_type: Literal['Histogram']


class Widget(RootModel[Union[PieChart, Histogram]]):
    root: Union[PieChart, Histogram] = Field(..., discriminator='widget_type')


class DataSource(BaseModel):
    host: str = Field(
        ..., description='Hostname or IP address of the data source server.'
    )
    port: int = Field(
        ..., description='Port number for connecting to the data source server.'
    )
    username: str = Field(..., description='Username for data source authentication.')
    password: Optional[str] = Field(
        None, description='Password for data source authentication.'
    )
    database: str = Field(..., description='Name of the database to connect to.')
    tables: List[DataSourceTable]


class UpdateDashboardPostRequest(DashboardCreate):
    dashboard_id: int


class Dashboard(BaseModel):
    dashboard_id: int = Field(..., description='Unique identifier for the dashboard.')
    title: str = Field(..., description='User-defined title of the dashboard.')
    widgets: List[Widget] = Field(
        ..., description='List of widgets included in the dashboard.'
    )
    dataSource: DataSource = Field(
        ...,
        description='Configuration of the data source associated with the dashboard.',
    )
